# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 934042abcde869d8cc6dc5902c2b02574ab68b83b482ed502be54d596fc74eb6be5c5970d8a50b8d6a90b17adc3bec94657c31bf656d4aa6cbb066fa144812b9

test:
  secret_key_base: a7e2ce4eed6556ae0073c744a7ac3c6de7c94f30028b32403134d14bdfb7290634b1e8dc02c6758ce1fb1069cb03f6b3f07454b314fbe3c6a661db9a2482b8ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
